# SSH Collector Pro 开发环境配置

# 服务器配置
server:
  host: "127.0.0.1"
  port: 18000
  mode: "debug"
  read_timeout: 60s
  write_timeout: 60s

# 采集器配置
collector:
  id: "collector-dev-001"
  type: "ssh"
  version: "1.0.0-dev"
  tags: ["development", "ssh"]
  threads: 5
  concurrent: 3
  # 原始输出过滤规则（按行移除）
  output_filter:
    prefixes:
      - "---- More ----"
      - "more"
    contains:
      - "--more--"
    case_insensitive: true
    trim_space: true
  # 交互配置：自动交互与错误提示
  interact:
    auto_interactions:
      - except_output: "do you want to save this config? yes/no"
        command_auto_send: "yes"
      - except_output: "do you want to reload this device? yes/no"
        command_auto_send: "no"
    error_hints:
      - "ERROR:"
      - "invalid parameters detect"
    case_insensitive: true
    trim_space: true


# 数据库配置
database:
  sqlite:
    path: "./data/collector_dev.db"
    max_idle_conns: 5
    max_open_conns: 50
    conn_max_lifetime: 3600s


# SSH配置
ssh:
  timeout: 30s
  keep_alive_interval: 10s
  max_sessions: 50


# 日志配置
log:
  level: "debug"
  format: "text"
  output: "both"
  file_path: "./log/collector_dev.log"
  max_size: 50
  max_backups: 3
  max_age: 7
  compress: false

# 采集数据存储（开发环境）
storage:
  minio:
    host: "127.0.0.1"
    port: 9000
    access_key: "minioadmin"
    secret_key: "minioadmin"
    bucket: "sshcollector-raw-dev"
    secure: false
  postgres:
    host: "127.0.0.1"
    port: 5432
    username: "postgres"
    password: "postgres"
    database: "sshcollector_dev"

# 格式化数据配置（仅定义 MinIO 路径前缀）
data_format:
  minio_prefix: "data-formats-dev"