# SSH Collector Pro 开发环境配置

# 服务器配置
server:
  host: "127.0.0.1"
  port: 8080
  mode: "debug"
  read_timeout: 60s
  write_timeout: 60s

# 采集器配置
collector:
  id: "collector-dev-001"
  type: "ssh"
  version: "1.0.0-dev"
  tags: ["development", "ssh"]
  threads: 5
  concurrent: 3

# 控制器配置
controller:
  host: "127.0.0.1"
  port: 9000
  register_retry: 3
  register_interval: 10s
  heartbeat_interval: 3s
  heartbeat_timeout: 9s

# 数据库配置
database:
  sqlite:
    path: "./data/collector_dev.db"
    max_idle_conns: 5
    max_open_conns: 50
    conn_max_lifetime: 3600s

# Redis配置
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 1
  pool_size: 5
  min_idle_conns: 2
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

# SSH配置
ssh:
  timeout: 30s
  keep_alive_interval: 10s
  max_sessions: 50

# XXL-Job配置
xxljob:
  admin_addresses: "http://127.0.0.1:8080/xxl-job-admin"
  access_token: ""
  app_name: "ssh-collector-dev"
  address: ""
  ip: ""
  port: 9998
  log_path: "./log/xxljob"
  log_retention_days: 7

# 日志配置
log:
  level: "debug"
  format: "text"
  output: "both"
  file_path: "./log/collector_dev.log"
  max_size: 50
  max_backups: 3
  max_age: 7
  compress: false