# SSH Collector Pro 生产环境配置

# 服务器配置
server:
  host: "0.0.0.0"
  port: 18000
  mode: "release"
  read_timeout: 60s
  write_timeout: 60s

# 采集器配置
collector:
  id: "${COLLECTOR_ID}"
  type: "ssh"
  version: "1.0.0"
  tags: ["production", "ssh"]
  threads: 20
  concurrent: 10
  # 原始输出过滤规则（按行移除）
  output_filter:
    prefixes:
      - "---- More ----"
      - "more"
    contains:
      - "--more--"
    case_insensitive: true
    trim_space: true
  # 交互配置：自动交互与错误提示
  interact:
    auto_interactions:
      - except_output: "do you want to save this config? yes/no"
        command_auto_send: "yes"
      - except_output: "do you want to reload this device? yes/no"
        command_auto_send: "no"
    error_hints:
      - "ERROR:"
      - "invalid parameters detect"
    case_insensitive: true
    trim_space: true


# 数据库配置
database:
  sqlite:
    path: "/data/collector.db"
    max_idle_conns: 20
    max_open_conns: 200
    conn_max_lifetime: 3600s


# SSH配置
ssh:
  timeout: 30s
  keep_alive_interval: 10s
  max_sessions: 200


# 日志配置
log:
  level: "info"
  format: "json"
  output: "file"
  file_path: "/logs/collector.log"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true

# 采集数据存储（生产环境）
storage:
  minio:
    host: "minio"
    port: 9000
    access_key: "${MINIO_ACCESS_KEY}"
    secret_key: "${MINIO_SECRET_KEY}"
    bucket: "sshcollector-raw"

# 格式化数据配置（仅定义 MinIO 路径前缀）
data_format:
  minio_prefix: "data-formats"
    secure: false
  postgres:
    host: "postgres"
    port: 5432
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    database: "sshcollector"